### ISSUE TITLE
Start app Fails

### ISSUE THREAD

**Issue by stefdaems** [imsardine/winappdriver#17]
Followed your tutorial in order to start Twitter application. Following error occurs every time.

![image](https://cloud.githubusercontent.com/assets/12783064/9355674/7e7c76ae-467b-11e5-86f1-6285b7edca7d.png)

Any idea what could be wrong? I'm using vb.net

desired = New DesiredCapabilities
desired.SetCapability("PlatformName", "WindowsModern")
desired.SetCapability("PackageName", "9E2F88E3.Twitter")

**Comment by imsardine** [comment]
@stefdaems Please check out [version 0.2.1](https://github.com/imsardine/winappdriver/releases/tag/v0.2.1). (note that you have to uninstall WinAppDriver first)

**Comment by wilcollins** [comment]
Same issue as #12
