### ISSUE TITLE
Win10 

### ISSUE THREAD

**Issue by stefdaems** [imsardine/winappdriver#21]
When executing the windappdriver on a win10 device following thing are happening.

App starts
but after several seconds it crashes.

ActivateStoreApp.exe error popup is showing

Console displays
system.invalidoperationexception the process must exit before getting the requested information
 at system.diagnostics.process.ensurestate(state state)
 at system.diagnostics.process.get_ExitCode()
 at winappdriver.modern.storeapp.Activate() 

I'm aware win10 is not fully supported, but I wanna be sure this error isn't caused by my setup

**Comment by imsardine** [comment]
I was able to activate a store app successfully.

I think this error (kind of timing issue) was introduced in 6187bc6. You can try to replace `process.WaitForExit(5 * 1000);` with `process.WaitForExit();`.

**Comment by stefdaems** [comment]
Solved

**Comment by wilcollins** [comment]
Still seeing this with Store Apps in #12
